### ISSUE TITLE
node-gyp build for minidump fails with KeyError

### ISSUE THREAD

**Issue by yurivict** [electron/node-minidump#11]
```
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 533, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 526, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 502, in gyp_main
    params, options.check, options.circular_check)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2756, in Load
    RemoveLinkDependenciesFromNoneTargets(targets)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1501, in RemoveLinkDependenciesFromNoneTargets
    if targets[t].get('variables', {}).get('link_dependency', 0):
KeyError: 'deps/breakpad/breakpad.gyp:dump_syms#target'
```

I also think you bundled some bad version of google-breakpad, with some .dll and .exe files in the repository.

**Comment by gnail** [comment]
Also have the same problem trying to install [mini-breakpad-server](https://github.com/electron/mini-breakpad-server) on Windows 7. Looking at [breakpad.gyp](https://github.com/electron/chromium-breakpad/blob/1e937567e92d2c3beed4556f3c68a4b0362b1e6d/breakpad.gyp) does it have build config for Windows at all? Is Windows not supported?

**Comment by gnail** [comment]
Got it working by installing minidump@^0.9.0 instead of 0.3.0 required by mini-breakpad-server
