### ISSUE TITLE
npm install minidump fail on centos 6

### ISSUE THREAD

**Issue by dengyaolong** [electron/node-minidump#27]
install fail. 
uname -a : 2.6.32-431.20.3.el6.mt20161028.x86_64 #1 SMP Fri Oct 28 17:50:35 CST 2016 x86_64 x86_64 x86_64 GNU/Linux
node version: 7.6
npm version: 4.1.2

How to solve this problem?

```
> minidump@0.11.0 install /home/dragon/crash/node_modules/minidump
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/dragon/crash/node_modules/minidump/build'
  CXX(host) Release/obj.host/dump_syms/deps/breakpad/src/common/dwarf/bytereader.o
  CXX(host) Release/obj.host/dump_syms/deps/breakpad/src/common/dwarf_cfi_to_module.o
  CXX(host) Release/obj.host/dump_syms/deps/breakpad/src/common/dwarf_cu_to_module.o
  CXX(host) Release/obj.host/dump_syms/deps/breakpad/src/common/dwarf/dwarf2diehandler.o
  CXX(host) Release/obj.host/dump_syms/deps/breakpad/src/common/dwarf/dwarf2reader.o
  CXX(host) Release/obj.host/dump_syms/deps/breakpad/src/common/dwarf/elf_reader.o
  CXX(host) Release/obj.host/dump_syms/deps/breakpad/src/common/dwarf_line_to_module.o
  CXX(host) Release/obj.host/dump_syms/deps/breakpad/src/common/language.o
  CXX(host) Release/obj.host/dump_syms/deps/breakpad/src/common/linux/crc32.o
  CXX(host) Release/obj.host/dump_syms/deps/breakpad/src/common/linux/dump_symbols.o
In file included from ../deps/breakpad/src/common/linux/file_id.h:40,
                 from ../deps/breakpad/src/common/linux/dump_symbols.cc:66:
../deps/breakpad/src/common/memory.h: In constructor ‘google_breakpad::PageStdAllocator<T>::PageStdAllocator(const google_breakpad::PageStdAllocator<Other>&)’:
../deps/breakpad/src/common/memory.h:181: error: ‘nullptr’ was not declared in this scope
make: *** [Release/obj.host/dump_syms/deps/breakpad/src/common/linux/dump_symbols.o] Error 1
make: Leaving directory `/home/dragon/crash/node_modules/minidump/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dragon/.nvm/versions/node/v7.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-431.20.3.el6.mt20161028.x86_64
gyp ERR! command "/home/dragon/.nvm/versions/node/v7.6.0/bin/node" "/home/dragon/.nvm/versions/node/v7.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dragon/crash/node_modules/minidump
gyp ERR! node -v v7.6.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN crash@1.0.0 No description
npm WARN crash@1.0.0 No repository field.
npm ERR! Linux 2.6.32-431.20.3.el6.mt20161028.x86_64
npm ERR! argv "/home/dragon/.nvm/versions/node/v7.6.0/bin/node" "/home/dragon/.nvm/versions/node/v7.6.0/bin/npm" "install" "minidump" "--save"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! minidump@0.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the minidump@0.11.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs minidump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dragon/crash/npm-debug.log
```

**Comment by dengyaolong** [comment]
it use `nullptr` , c++11 feature, require gcc 4.8, but my gcc version is 4.7. so, i rewrite nullptr => NULL, and it works!
