### ISSUE TITLE
install error on latest version 

### ISSUE THREAD

**Issue by leiming** [electron/node-minidump#51]
```sh
mkdir install_minidump_demo
 yarn init -y
 yarn add minidump
```

```sh
yarn add v1.22.18
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error C:\Users\bingzhang\devspace\install_minidump_demo\node_modules\minidump: Command failed.
Exit code: 1
Command: node build.js
Arguments:
Directory: C:\Users\bingzhang\devspace\install_minidump_demo\node_modules\minidump
Output:
C:\Users\bingzhang\devspace\install_minidump_demo\node_modules\minidump\build.js:24
  if (result.error) throw result.error
                    ^

Error: spawnSync C:\Users\bingzhang\devspace\install_minidump_demo\node_modules\minidump\deps\breakpad\configure ENOENT
    at Object.spawnSync (node:internal/child_process:1111:20)
    at Object.spawnSync (node:child_process:814:24)
    at spawnSync (C:\Users\bingzhang\devspace\install_minidump_demo\node_modules\minidump\build.js:23:31)
    at Object.<anonymous> (C:\Users\bingzhang\devspace\install_minidump_demo\node_modules\minidump\build.js:42:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawnSync C:\\Users\\bingzhang\\devspace\\install_minidump_demo\\node_modules\\minidump\\deps\\breakpad\\configure',
  path: 'C:\\Users\\bingzhang\\devspace\\install_minidump_demo\\node_modules\\minidump\\deps\\breakpad\\configure',
  spawnargs: []
}
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

![image](https://user-images.githubusercontent.com/2059859/171079857-fe2d8a17-1681-42c5-b877-8df623554c45.png)

**Comment by songming43** [comment]
I meet the same problem when i use node 16.0.0 on windows 10

**Comment by Kenny1zhao** [comment]
I meet the same problem on Windows 11

**Comment by diong** [comment]
not support win32
