### ISSUE TITLE
node-gyp rebiuld of minidump@0.8.0 fails with clang on debian

### ISSUE THREAD

**Issue by victorhaggqvist** [electron/node-minidump#7]
Just found out that the node-gyp rebiuld of minidump@0.8.0 fails on clang. Changing default `cc` and `cc+` to `gcc`.

The actual fail is `clang: error: unknown argument: '-fno-tree-sink'`.

Logs and info

```
$ ./script/build
Node: v0.10.35
npm: v1.4.28
Installing build modules...
clang: error: unknown argument: '-fno-tree-sink'
make: *** [Release/obj.target/minidump_stackwalk/deps/breakpad/src/third_party/libdisasm/ia32_implicit.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/n_node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/opt/n_node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/victor/Downloads/atmmm/build/node_modules/minidump
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! minidump@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the minidump@0.8.0 install script.
npm ERR! This is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "--userconfig=/home/victor/Downloads/atmmm/.npmrc" "install" "--quiet"
npm ERR! cwd /home/victor/Downloads/atmmm/build
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
1:36.10s total, 44.93s user, 4.38s system, 51% cpu

$ clang -v
Debian clang version 3.5.0-9 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: x86_64-pc-linux-gnu
Thread model: posix

$ node --version
 v0.10.35

$ npm --version
1.4.28

$ uname -a
Linux minos 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 GNU/Linux
```

**Comment by zcbenz** [comment]
The `-fno-tree-sink` argument is appended by Node, are you able to build other native modules like `runas` or `pathwatcher`?

**Comment by victorhaggqvist** [comment]
Yes, it appears so. Here is installs of `runas`, `pathwatcher` and `minidump` with clang as cc and c++.
```
~/Downloads/nodetest
$ npm install runas
|
> runas@1.0.1 install /home/victor/Downloads/nodetest/node_modules/runas
> node-gyp rebuild

make: Entering directory '/home/victor/Downloads/nodetest/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
  CXX(target) Release/obj.target/runas/src/runas_posix.o
  CXX(target) Release/obj.target/runas/src/fork.o
  SOLINK_MODULE(target) Release/obj.target/runas.node
  SOLINK_MODULE(target) Release/obj.target/runas.node: Finished
  COPY Release/runas.node
make: Leaving directory '/home/victor/Downloads/nodetest/node_modules/runas/build'
runas@1.0.1 node_modules/runas
└── nan@1.2.0

~/Downloads/nodetest
$ npm install pathwatcher
-
> pathwatcher@2.5.0 install /home/victor/Downloads/nodetest/node_modules/pathwatcher
> node-gyp rebuild

make: Entering directory '/home/victor/Downloads/nodetest/node_modules/pathwatcher/build'
  CXX(target) Release/obj.target/pathwatcher/src/main.o
  CXX(target) Release/obj.target/pathwatcher/src/common.o
  CXX(target) Release/obj.target/pathwatcher/src/handle_map.o
  CXX(target) Release/obj.target/pathwatcher/src/pathwatcher_linux.o
  SOLINK_MODULE(target) Release/obj.target/pathwatcher.node
  SOLINK_MODULE(target) Release/obj.target/pathwatcher.node: Finished
  COPY Release/pathwatcher.node
make: Leaving directory '/home/victor/Downloads/nodetest/node_modules/pathwatcher/build'
pathwatcher@2.5.0 node_modules/pathwatcher
├── nan@1.2.0
├── q@1.0.1
├── async@0.2.10
└── iconv-lite@0.4.6

~/Downloads/nodetest
$ npm install minidump
-
> minidump@0.9.0 install /home/victor/Downloads/nodetest/node_modules/minidump
> node-gyp rebuild

make: Entering directory '/home/victor/Downloads/nodetest/node_modules/minidump/build'
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf/bytereader.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf_cfi_to_module.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf_cu_to_module.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf/dwarf2diehandler.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf/dwarf2reader.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf_line_to_module.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/language.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/linux/crc32.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/linux/dump_symbols.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/linux/elf_symbols_to_module.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/linux/elfutils.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/linux/file_id.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/linux/linux_libc_support.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/linux/memory_mapped_file.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/module.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/stabs_reader.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/stabs_to_module.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/tools/linux/dump_syms/dump_syms.o
  LINK(target) Release/dump_syms
  LINK(target) Release/dump_syms: Finished
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/basic_code_modules.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/basic_source_line_resolver.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/binarystream.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/call_stack.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/cfi_frame_info.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/disassembler_x86.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/dump_context.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/dump_object.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/logging.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/pathname_stripper.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/process_state.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/simple_symbol_supplier.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/source_line_resolver_base.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stack_frame_cpu.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stack_frame_symbolizer.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalk_common.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker_amd64.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker_arm.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker_arm64.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker_mips.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker_ppc.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker_ppc64.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker_sparc.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker_x86.o
  CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/tokenize.o
  CC(target) Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/ia32_implicit.o
clang: error: unknown argument: '-fno-tree-sink'
deps/breakpad/stackwalk_common.target.mk:131: recipe for target 'Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/ia32_implicit.o' failed
make: *** [Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/ia32_implicit.o] Error 1
make: Leaving directory '/home/victor/Downloads/nodetest/node_modules/minidump/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/n_node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/opt/n_node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/victor/Downloads/nodetest/node_modules/minidump
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! minidump@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the minidump@0.9.0 install script.
npm ERR! This is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "minidump"
npm ERR! cwd /home/victor/Downloads/nodetest
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
35.862s total, 28.71s user, 2.16s system, 86% cpu
```

**Comment by ForbesLindesay** [comment]
I'm getting the same error when trying to build thread-sleep (https://travis-ci.org/ForbesLindesay/thread-sleep/jobs/47113045).  It's my first attempt at publishing a native module for node and so far I have it building on windows (locally and on appveyor) and mac (locally and on travis).   I can't get it building on travis running linux and I haven't yet got as far as trying to build it locally.  I'm tracking the issue at https://github.com/ForbesLindesay/thread-sleep/issues/2.  Any help at all would be appreciated.

**Comment by TimothyGu** [comment]
This is probably related to https://github.com/joyent/node/blob/v0.10.35/common.gypi#L81-L86, then joyent/node@84590f3fe9507887cebdcc11b3d1bc93180dc5a7 and joyent/node@2786737417810c0a4f0b70ac80a9c298486de355.

**Comment by TimothyGu** [comment]
One work around is grep for `'clang%': 0` and sed it to `:1` in `~/.node-gyp/0.10.25/common.gypi`.

**Comment by TimothyGu** [comment]
The real solution is surprisingly simple:

```
export CC=clang CXX=clang++
npm install --clang=1
```
