### ISSUE TITLE
Windows 11 installation failure

### ISSUE THREAD

**Issue by join-xiaohui** [electron/node-minidump#71]
PS C:\Users\Administrator\Desktop\unexpected_exit> npm install minidump
npm ERR! code 128
npm ERR! path C:\Users\Administrator\Desktop\unexpected_exit\node_modules\minidump
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c yarn submodule && node build.js
npm ERR! yarn run v1.22.19
npm ERR! $ git submodule update --init --recursive
PS C:\Users\Administrator\Desktop\unexpected_exit> npm i electron-minidump
npm ERR! code 1
npm ERR! path C:\Users\Administrator\Desktop\unexpected_exit\node_modules\minidump
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node build.js
npm ERR! C:\Users\Administrator\Desktop\unexpected_exit\node_modules\minidump\build.js:24
npm ERR!   if (result.error) throw result.error
npm ERR!                     ^
npm ERR!
npm ERR! Error: spawnSync C:\Users\Administrator\Desktop\unexpected_exit\node_modules\minidump\deps\breakpad\configure ENOENT
npm ERR!     at Object.spawnSync (node:internal/child_process:1117:20)
npm ERR!     at Object.spawnSync (node:child_process:871:24)
npm ERR!     at spawnSync (C:\Users\Administrator\Desktop\unexpected_exit\node_modules\minidump\build.js:23:31)
npm ERR!     at Object.<anonymous> (C:\Users\Administrator\Desktop\unexpected_exit\node_modules\minidump\build.js:42:1)
PS C:\Users\Administrator\Desktop\unexpected_exit> npm i electron-minidump@latest -S
npm ERR! code 1
npm ERR! path C:\Users\Administrator\Desktop\unexpected_exit\node_modules\minidump
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node build.js
npm ERR! C:\Users\Administrator\Desktop\unexpected_exit\node_modules\minidump\build.js:24
npm ERR!   if (result.error) throw result.error
npm ERR!                     ^
npm ERR!
npm ERR! Error: spawnSync C:\Users\Administrator\Desktop\unexpected_exit\node_modules\minidump\deps\breakpad\configure ENOENT
npm ERR!     at Object.spawnSync (node:internal/child_process:1117:20)
npm ERR!     at Object.spawnSync (node:child_process:871:24)
npm ERR!     at spawnSync (C:\Users\Administrator\Desktop\unexpected_exit\node_modules\minidump\build.js:23:31)
npm ERR!     at Object.<anonymous> (C:\Users\Administrator\Desktop\unexpected_exit\node_modules\minidump\build.js:42:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1275:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1133:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:972:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
npm ERR!     at node:internal/main/run_main_module:23:47 {
npm ERR!   errno: -4058,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'spawnSync C:\\Users\\Administrator\\Desktop\\unexpected_exit\\node_modules\\minidump\\deps\\breakpad\\configure',
npm ERR!   path: 'C:\\Users\\Administrator\\Desktop\\unexpected_exit\\node_modules\\minidump\\deps\\breakpad\\configure',
npm ERR!   spawnargs: []
npm ERR! }
npm ERR!
npm ERR! Node.js v19.9.0

**Comment by join-xiaohui** [comment]
#61 This doesn't seem to work for me

**Comment by Koppel-Zhou** [comment]
Is there anyone could help us?

**Comment by zouyn** [comment]
Is there anyone could help us?

**Comment by Jimbly** [comment]
This appears to have started as of 4c13f7b.

Prior to this version installs of `minidump` would effectively silently fail to build the binaries on Windows (allowing you to successfully install a package that references it), and then later error upon invocation (which well-behaved consumers of this library would already be handling, as running `minidump_stackwalk` on a untrusted-user-uploaded file will occasionally error regardless).

I've made a tweak in my fork in e61e52c to effectively restore this behavior.  It's unclear if this is generally desired or not - if someone is explicitly requiring this library for it's purpose, delaying the error until run-time may not be desired, however if someone is simply requiring this library as a dependency because they are, for instance, doing development work on [simple-breakpad-server](https://github.com/acrisci/simple-breakpad-server) on a Windows host, then this solves their problem.  I'll make a PR if the maintainers express interest.  Ideal solution would be to change the build process to work on Windows (swap manual calls to `configure` and `make` to `node-gyp` instead, or something similar), but that's outside my area of experience.

If anyone wants a quick fix (silently fail to build the binaries on Windows), feel free to grab [`@jimbly/minidump`](https://www.npmjs.com/package/@jimbly/minidump) in the meantime (also includes the other two fixes/PRs I made).
